<?php

use Illuminate\Database\Seeder;

class TaxaTableSeeder3 extends Seeder
{
    public function run()
    {
        DB::table('taxa')->insert([
			["id" => 12460, "taxon_sort" => 12501, "taxon_id" => 12489, "taxon_category_id" => 6, "name" => "tricolor", "english_name" => "", "created_by" => "System"],
			["id" => 12461, "taxon_sort" => 12502, "taxon_id" => 12489, "taxon_category_id" => 6, "name" => "fulgora", "english_name" => "", "created_by" => "System"],
			["id" => 15421, "taxon_sort" => 10556, "taxon_id" => 15423, "taxon_category_id" => 6, "name" => "chromus", "english_name" => "", "created_by" => "System"],
			["id" => 15422, "taxon_sort" => 10557, "taxon_id" => 15423, "taxon_category_id" => 6, "name" => "priene", "english_name" => "", "created_by" => "System"],
			["id" => 15424, "taxon_sort" => 10559, "taxon_id" => 15429, "taxon_category_id" => 6, "name" => "amphimachus", "english_name" => "", "created_by" => "System"],
			["id" => 15425, "taxon_sort" => 10560, "taxon_id" => 15429, "taxon_category_id" => 6, "name" => "amphiktion", "english_name" => "", "created_by" => "System"],
			["id" => 15426, "taxon_sort" => 10561, "taxon_id" => 15429, "taxon_category_id" => 6, "name" => "baroni", "english_name" => "", "created_by" => "System"],
			["id" => 15427, "taxon_sort" => 10562, "taxon_id" => 15429, "taxon_category_id" => 6, "name" => "pseudomeander", "english_name" => "", "created_by" => "System"],
			["id" => 15428, "taxon_sort" => 10563, "taxon_id" => 15429, "taxon_category_id" => 6, "name" => "symaithus", "english_name" => "", "created_by" => "System"],
			["id" => 15430, "taxon_sort" => 10565, "taxon_id" => 15432, "taxon_category_id" => 6, "name" => "camilla", "english_name" => "", "created_by" => "System"],
			["id" => 15431, "taxon_sort" => 10566, "taxon_id" => 15432, "taxon_category_id" => 6, "name" => "metabus", "english_name" => "", "created_by" => "System"],
			["id" => 15434, "taxon_sort" => 10569, "taxon_id" => 15439, "taxon_category_id" => 6, "name" => "demophon", "english_name" => "", "created_by" => "System"],
			["id" => 15435, "taxon_sort" => 10570, "taxon_id" => 15439, "taxon_category_id" => 6, "name" => "centralis", "english_name" => "", "created_by" => "System"],
			["id" => 15436, "taxon_sort" => 10571, "taxon_id" => 15439, "taxon_category_id" => 6, "name" => "muson", "english_name" => "", "created_by" => "System"],
			["id" => 15437, "taxon_sort" => 10572, "taxon_id" => 15439, "taxon_category_id" => 6, "name" => "occidentalis", "english_name" => "", "created_by" => "System"],
			["id" => 15438, "taxon_sort" => 10573, "taxon_id" => 15439, "taxon_category_id" => 6, "name" => "thalpius", "english_name" => "", "created_by" => "System"],
			["id" => 15440, "taxon_sort" => 10575, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "demophoon", "english_name" => "", "created_by" => "System"],
			["id" => 15441, "taxon_sort" => 10576, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "andicola", "english_name" => "", "created_by" => "System"],
			["id" => 15442, "taxon_sort" => 10577, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "antimache", "english_name" => "", "created_by" => "System"],
			["id" => 15443, "taxon_sort" => 10578, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "crassina", "english_name" => "", "created_by" => "System"],
			["id" => 15444, "taxon_sort" => 10579, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "gulina", "english_name" => "", "created_by" => "System"],
			["id" => 15445, "taxon_sort" => 10580, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "insulicola", "english_name" => "", "created_by" => "System"],
			["id" => 15446, "taxon_sort" => 10581, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "ramosorum", "english_name" => "", "created_by" => "System"],
			["id" => 15447, "taxon_sort" => 10582, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "mexicana", "english_name" => "", "created_by" => "System"],
			["id" => 15448, "taxon_sort" => 10583, "taxon_id" => 15451, "taxon_category_id" => 5, "name" => "demophoon", "english_name" => "", "created_by" => "System"],
			["id" => 15449, "taxon_sort" => 10584, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "licomedes", "english_name" => "", "created_by" => "System"],
			["id" => 15450, "taxon_sort" => 10585, "taxon_id" => 15451, "taxon_category_id" => 6, "name" => "pacifica", "english_name" => "", "created_by" => "System"],
			["id" => 15452, "taxon_sort" => 10587, "taxon_id" => 15456, "taxon_category_id" => 6, "name" => "meander", "english_name" => "", "created_by" => "System"],
			["id" => 15453, "taxon_sort" => 10588, "taxon_id" => 15456, "taxon_category_id" => 6, "name" => "castorina", "english_name" => "", "created_by" => "System"],
			["id" => 15454, "taxon_sort" => 10589, "taxon_id" => 15456, "taxon_category_id" => 6, "name" => "megabates", "english_name" => "", "created_by" => "System"],
			["id" => 15455, "taxon_sort" => 10590, "taxon_id" => 15456, "taxon_category_id" => 6, "name" => "phoebus", "english_name" => "", "created_by" => "System"],
			["id" => 15457, "taxon_sort" => 10592, "taxon_id" => 15459, "taxon_category_id" => 6, "name" => "aelia", "english_name" => "", "created_by" => "System"],
			["id" => 15458, "taxon_sort" => 10593, "taxon_id" => 15459, "taxon_category_id" => 6, "name" => "phaedra", "english_name" => "", "created_by" => "System"],
			["id" => 15461, "taxon_sort" => 10597, "taxon_id" => 15464, "taxon_category_id" => 6, "name" => "dexamenus", "english_name" => "", "created_by" => "System"],
			["id" => 15462, "taxon_sort" => 10598, "taxon_id" => 15464, "taxon_category_id" => 6, "name" => "leuctra", "english_name" => "", "created_by" => "System"],
			["id" => 15463, "taxon_sort" => 10599, "taxon_id" => 15464, "taxon_category_id" => 6, "name" => "medinai", "english_name" => "", "created_by" => "System"],
			["id" => 15465, "taxon_sort" => 10601, "taxon_id" => 15467, "taxon_category_id" => 6, "name" => "demodice", "english_name" => "", "created_by" => "System"],
			["id" => 15466, "taxon_sort" => 10602, "taxon_id" => 15467, "taxon_category_id" => 6, "name" => "louisa", "english_name" => "", "created_by" => "System"],
			["id" => 15470, "taxon_sort" => 10606, "taxon_id" => 15477, "taxon_category_id" => 6, "name" => "pylene", "english_name" => "", "created_by" => "System"],
			["id" => 15471, "taxon_sort" => 10607, "taxon_id" => 15477, "taxon_category_id" => 6, "name" => "bahiana", "english_name" => "", "created_by" => "System"],
			["id" => 15472, "taxon_sort" => 10608, "taxon_id" => 15477, "taxon_category_id" => 6, "name" => "eugenes", "english_name" => "", "created_by" => "System"],
			["id" => 15473, "taxon_sort" => 10609, "taxon_id" => 15477, "taxon_category_id" => 6, "name" => "gnorima", "english_name" => "", "created_by" => "System"],
			["id" => 15474, "taxon_sort" => 10610, "taxon_id" => 15477, "taxon_category_id" => 6, "name" => "jordani", "english_name" => "", "created_by" => "System"],
			["id" => 15475, "taxon_sort" => 10611, "taxon_id" => 15477, "taxon_category_id" => 6, "name" => "laertides", "english_name" => "", "created_by" => "System"],
			["id" => 15476, "taxon_sort" => 10612, "taxon_id" => 15477, "taxon_category_id" => 6, "name" => "philetas", "english_name" => "", "created_by" => "System"],
			["id" => 15478, "taxon_sort" => 10614, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "lambertoana", "english_name" => "", "created_by" => "System"],
			["id" => 15479, "taxon_sort" => 10615, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "ibarra", "english_name" => "", "created_by" => "System"],
			["id" => 15480, "taxon_sort" => 10616, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "brooksiana", "english_name" => "", "created_by" => "System"],
			["id" => 15481, "taxon_sort" => 10617, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "escalantiana", "english_name" => "", "created_by" => "System"],
			["id" => 15482, "taxon_sort" => 10618, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "diaziana", "english_name" => "", "created_by" => "System"],
			["id" => 15483, "taxon_sort" => 10619, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "salvadora", "english_name" => "", "created_by" => "System"],
			["id" => 15484, "taxon_sort" => 10620, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "lygia", "english_name" => "", "created_by" => "System"],
			["id" => 15485, "taxon_sort" => 10621, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "photidia", "english_name" => "", "created_by" => "System"],
			["id" => 15486, "taxon_sort" => 10622, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "sphacteria", "english_name" => "", "created_by" => "System"],
			["id" => 15487, "taxon_sort" => 10623, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "neoterpe", "english_name" => "", "created_by" => "System"],
			["id" => 15488, "taxon_sort" => 10624, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "deiphile", "english_name" => "", "created_by" => "System"],
			["id" => 15489, "taxon_sort" => 10625, "taxon_id" => 15490, "taxon_category_id" => 6, "name" => "xenagoras", "english_name" => "", "created_by" => "System"],
			["id" => 15491, "taxon_sort" => 10627, "taxon_id" => 15498, "taxon_category_id" => 6, "name" => "praeneste", "english_name" => "", "created_by" => "System"],
			["id" => 15492, "taxon_sort" => 10628, "taxon_id" => 15498, "taxon_category_id" => 6, "name" => "abrupta", "english_name" => "", "created_by" => "System"],
			["id" => 15493, "taxon_sort" => 10629, "taxon_id" => 15498, "taxon_category_id" => 6, "name" => "buckleyana", "english_name" => "", "created_by" => "System"],
			["id" => 15494, "taxon_sort" => 10630, "taxon_id" => 15498, "taxon_category_id" => 6, "name" => "choroniensis", "english_name" => "", "created_by" => "System"],
			["id" => 15495, "taxon_sort" => 10631, "taxon_id" => 15498, "taxon_category_id" => 6, "name" => "confusa", "english_name" => "", "created_by" => "System"],
			["id" => 15496, "taxon_sort" => 10632, "taxon_id" => 15498, "taxon_category_id" => 6, "name" => "isabelae", "english_name" => "", "created_by" => "System"],
			["id" => 15497, "taxon_sort" => 10633, "taxon_id" => 15498, "taxon_category_id" => 6, "name" => "virago", "english_name" => "", "created_by" => "System"],
			["id" => 15503, "taxon_sort" => 11522, "taxon_id" => 15508, "taxon_category_id" => 6, "name" => "doraete", "english_name" => "", "created_by" => "System"],
			["id" => 15504, "taxon_sort" => 11523, "taxon_id" => 15508, "taxon_category_id" => 6, "name" => "antissa", "english_name" => "", "created_by" => "System"],
			["id" => 15505, "taxon_sort" => 11524, "taxon_id" => 15508, "taxon_category_id" => 6, "name" => "enipeus", "english_name" => "", "created_by" => "System"],
			["id" => 15506, "taxon_sort" => 11525, "taxon_id" => 15508, "taxon_category_id" => 6, "name" => "gideon", "english_name" => "", "created_by" => "System"],
			["id" => 15507, "taxon_sort" => 11526, "taxon_id" => 15508, "taxon_category_id" => 6, "name" => "quasinegra", "english_name" => "", "created_by" => "System"],
			["id" => 15509, "taxon_sort" => 11528, "taxon_id" => 15511, "taxon_category_id" => 6, "name" => "dorinda", "english_name" => "", "created_by" => "System"],
			["id" => 15510, "taxon_sort" => 11529, "taxon_id" => 15511, "taxon_category_id" => 6, "name" => "whitelyi", "english_name" => "", "created_by" => "System"],
			["id" => 15512, "taxon_sort" => 15467, "taxon_id" => 17253, "taxon_category_id" => 5, "name" => "syrna", "english_name" => "", "created_by" => "System"]
		]);
	}
}